### ISSUE TITLE
dry run

### ISSUE THREAD

**Issue by burningTyger** [andreaskoch/dcsg#9]
Great script!

Could you add a --dry option so that I can check what is written into my systemd directory?

**Comment by joelnb** [comment]
Hi, I had a stab at this & would appreciate any comments if you are still interested: https://github.com/andreaskoch/dcsg/pull/10

**Comment by burningTyger** [comment]
Hi and thank you very much. I don't have anything right now but will need this later on. This is a super handy tool!
